# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
  - name: PROJECT_PATH
    value: "src/webshop-frontend/"

  - name: APP_NAME
    value: "webshop-app"

  - name: SHARED_LIB
    value: "shared-lib"

  - name: SHARED_LIB_DIST_PATH
    value: "src/webshop-frontend/dist/shared-lib/"

  - name: IS_MASTER
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "qa_stage"
    displayName: "QA Stage"
    jobs:
      - job: "prepare_job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              ls -al
              ls -al ${{ variables.PROJECT_PATH }}
              ls -al ${{ variables.PROJECT_PATH }}/projects
            displayName: "DEBUG"

          - task: Npm@1
            displayName: "Install"
            inputs:
              command: "custom"
              customCommand: "install"
              workingDir: ${{ variables.PROJECT_PATH }}

          - task: Npm@1
            displayName: "Test ${{ variables.APP_NAME }}"
            inputs:
              command: "custom"
              customCommand: "run test ${{ variables.APP_NAME }}"
              workingDir: ${{ variables.PROJECT_PATH }}

          - task: Npm@1
            displayName: "Test ${{ variables.SHARED_LIB }}"
            inputs:
              command: "custom"
              customCommand: "run test ${{ variables.SHARED_LIB }}"
              workingDir: ${{ variables.PROJECT_PATH }}

  - stage: "build_app_stage"
    displayName: "RELEASE Stage"
    dependsOn: ["qa_stage"]
    condition: and(succeeded(), eq(variables.IS_MASTER, 'true'))
    jobs:
      - job: "prepare_job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              ls -al
              ls -al ${{ variables.PROJECT_PATH }}
              ls -al ${{ variables.PROJECT_PATH }}/projects
            displayName: "DEBUG"

          - task: Npm@1
            displayName: "Install"
            inputs:
              command: "custom"
              customCommand: "install"
              workingDir: ${{ variables.PROJECT_PATH }}

          - task: Npm@1
            displayName: "Build release"
            inputs:
              command: "custom"
              customCommand: "run build ${{ variables.APP_NAME }}"
              workingDir: ${{ variables.PROJECT_PATH }}

  - stage: "publish_stage"
    displayName: "PUBLISH Stage"
    dependsOn: ["qa_stage", "build_app_stage"] # Parallelisierung
    jobs:
      - job: "prepare_job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              ls -al
              ls -al ${{ variables.PROJECT_PATH }}
              ls -al ${{ variables.PROJECT_PATH }}/projects
            displayName: "DEBUG"

          - task: Npm@1
            displayName: "Install"
            inputs:
              command: "custom"
              customCommand: "install"
              workingDir: ${{ variables.PROJECT_PATH }}

          - task: Npm@1
            displayName: "Build release"
            inputs:
              command: "custom"
              customCommand: "run build ${{ variables.SHARED_LIB }}"
              workingDir: ${{ variables.PROJECT_PATH }}

          - task: Npm@1
            displayName: "Publish release"
            inputs:
              command: "custom"
              customCommand: "publish ${{ variables.SHARED_LIB_DIST_PATH }}"
              workingDir: ${{ variables.PROJECT_PATH }}
